name: arke-toDoList

services:
  arke.todolist.api:
    image: todoapi
    build:
      context: .
      dockerfile: Arke.ToDoList.API/Dockerfile
    ports:
      - 6500:80
    environment:
      ASPNETCORE_ENVIRONMENT: "Local"
      ASPNETCORE_URLS: "http://0.0.0.0:80"
